### ISSUE TITLE
Smooth slider

### ISSUE THREAD

**Issue by kinafu** [terkelg/zuckerberg.smile#4]
Currently you can control the amount of smiley in only 10 steps.

It would be interesting to try a smooth control without steps.

Maybe one could use a video to get the image data and thus have a lot of time stamps.

It's just an idea, maybe the effect is more interesting with just the 10-steps slider.

**Comment by terkelg** [comment]
You won't be able to get it much smoother than it currently Is. You can't easily skip frame by frame in videos on the web
